# -*- coding: utf-8 -*-
"""punctuation_ARABIC_NLP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CW8XhlUjwDD4uXP-Q0I_FcU40CDbWXDU
"""

from google.colab import output
output.disable_custom_widget_manager()

!wget "https://data.mendeley.com/public-files/datasets/2pkxckwgs3/files/4f402c76-388e-4bde-b887-f1be522001db/file_downloaded"

!unzip file_downloaded -d dataset

import os
import re
import pandas as pd
import numpy as np

folder = "dataset/SSAC-UNPC"
doc = []
for file in os.listdir(folder):
    file_path = os.path.join(folder, file)
    with open(file_path, "r", encoding="utf-8") as f:
        lines = f.readlines()
        doc.append(lines)
    # for i in range(10):
    #   print(lines[i],'\n')
    # print('\n')

print('Number of documents:',len(doc),'\n','Number of phrase in one document: ',len(lines))

"""

>  # To convert the Input text to output sequence word and the punks come after each word"""

def encoding_word(texts):
  words_without_puncts = []
  leabels = []
  l_id=[]
  punct = {'.':1,'،':2,'؟':3,'!':4,':':5,'؛':6,' ':0}
  # for text in texts:
  words = texts.split()
  for word in words:
    match = re.match(r"(.*?)([،\.\؟\!\:\؛])?$", word)
    clean = match.group(1)
    puncts_in_phrase = match.group(2) or " "
    words_without_puncts.append(clean)
    leabels.append(puncts_in_phrase)
    # print(leabels)
  l_id=[punct[p] for p in leabels]
  df = pd.DataFrame({
  "word": words_without_puncts,
  "punct": leabels,
  "label_id": l_id
  })
  return df

"""**Create a CSV file for the dataset after sequential the data**"""

def process(line):
  filename = "dataset.csv"
  if not os.path.exists(filename):
      line.to_csv(filename, index=False, encoding="utf-8")
  else:
      line.to_csv(filename, index=False, encoding="utf-8", header=False, mode="a")
  # print(df.path)

"""لتسهيل التعامل مع البيانات تم تحويلها إلى ملف csv"""

import os
folder = "dataset/SSAC-UNPC"
doc = []
batch_size = 50000
batch = []
# df=pd.DataFrame()
for file in os.listdir(folder):
    file_path = os.path.join(folder, file)
    with open(file_path, "r", encoding="utf-8") as f:
        # lines = f.readlines()
        for line in f:
          # print(line)
          # break
          ds =encoding_word(line)
          batch.append(ds)
          if len(batch) >= batch_size:
            pd_batch = pd.concat(batch)
            process(pd_batch)
            batch = []

          # process(ds)
        # doc.append(lines)
    # for i in range(10):
    #   print(lines[i],'\n')
    # print('\n')

from google.colab import drive
drive.mount('/content/drive')

!cp dataset.csv /content/drive/MyDrive/F_dataset

"""#**CODE START HERE**"""

!pip install -qq gdown

"""**Get some data from the dataset as chunks to prevent Colab crush and saving time**"""

import pandas as pd
import gdown
# https://drive.google.com/file/d/1sQppeJ4RMzuUmwaZFe7Xfa2q8kiImWR6/view?usp=sharing
url = "https://drive.google.com/uc?id=1sQppeJ4RMzuUmwaZFe7Xfa2q8kiImWR6"

temp_path = "/tmp/dataset.csv"

gdown.download(url, temp_path, quiet=False)

chunks = pd.read_csv(temp_path, chunksize=200000)

# for chunk in chunks:
#     print(chunk.sample(10))# || PRINT SOME SAMPLES ||
#     break

"""بدلاً من استخدام كامل الداتا استخدمنا جزء منها حتى نتمكن من التعامل مع محدودية colab

"""

for chunk in chunks:
    print(chunk.sample(20))# || PRINT SOME SAMPLES ||
    break

X = chunk["word"].tolist()
Y = chunk["label_id"].tolist()
for i in range(100):
  if(Y[i] == 4):
    continue
  print('X labels: ',X[i],'\n','Y labels: ',Y[i],'\n')

"""sequence the words to phrase as any phrase end with one of ( '.' , '؟' , '!' )"""

def sequence(words,labels):
  X=[]
  Y=[]
  phrase = []
  phrase_labels = []
  # punct = {'.':1,'،':2,'؟':3,'!':4,':':5,'؛':6,' ':0}

  for word , label in zip(words , labels):
    phrase.append(word)
    phrase_labels.append(label)
    if label in [1,3,4]: # . or ؟ or !
      X.append(phrase)
      Y.append(phrase_labels)
      phrase=[]
      phrase_labels=[]
  if len(phrase)>0:
    X.append(phrase)
    Y.append(phrase_labels)

  return X,Y

X , Y = sequence(X,Y)

for i in range (3):
  print(X[i],'\n',Y[i],'\n')

"""**First i need to remove the < nan > samples to prevent errors while creating embedding**"""

clean_X = []
clean_Y = []

for sent, labels in zip(X, Y):
    if isinstance(sent, list):
        new_sent = []
        new_labels = []
        for w, l in zip(sent, labels):
            if isinstance(w, str) and w.strip() != "":
                new_sent.append(w)
                new_labels.append(l)

        if len(new_sent) > 0:
            clean_X.append(new_sent)
            clean_Y.append(new_labels)
print("deleting samples: " ,len(X)-len(clean_X))
X = clean_X
Y = clean_Y

"""في بعض الحالات كان ضمن البيانات قيم NaN وتسببت في عرقلة التدريب وإنشاء embedding لهذا قمنا بحذف كل قيم NaN مع label لها

"""

!pip install tensorflow

"""**Tokeniz the words using keras tokenizer**"""

from tensorflow.keras.preprocessing.text import Tokenizer

tokenizer = Tokenizer(oov_token="<UNK>")
tokenizer.fit_on_texts(X)

"""**transform text to sequence number**"""

X_seq_num = tokenizer.texts_to_sequences(X)

X_seq_num[1]

"""**Padding to max length of the phrases**"""

from tensorflow.keras.preprocessing.sequence import pad_sequences

max_len = max(len(s) for s in X_seq_num)

X_padded = pad_sequences(X_seq_num, maxlen=max_len, padding="post")
Y_padded = pad_sequences(Y, maxlen=max_len, padding="post")

"""# To start traning we need to decide whitch model is work for our problem
**First will be LSTM**

It understand the Chronological order of words
and desgine for the sequence problem
"""

from sklearn.model_selection import train_test_split

X_train , X_test, Y_train ,Y_test = train_test_split(X_padded,Y_padded,test_size = 0.2)

print(X_train[0])
print(X_test[0])
print(Y_train[0])
print(Y_test[0])

"""**To ignor the zeros in the padded data while compute the accuracy**"""

import tensorflow as tf
def masked_accuracy(y_true, y_pred):
    y_pred = tf.argmax(y_pred, axis=-1, output_type=tf.int64)
    y_true = tf.cast(y_true, tf.int64)

    mask = tf.not_equal(y_true, 0)
    matches = tf.equal(y_true, y_pred)
    matches = tf.logical_and(mask, matches)

    return tf.reduce_sum(tf.cast(matches, tf.float32)) / tf.reduce_sum(tf.cast(mask, tf.float32))

"""

# 1. prepare LSTM model


"""

MAX_LEN = max(len(s) for s in X_train)
Classes = 7
voc_size = len(tokenizer.word_index)+1

from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Embedding, LSTM, Dense, TimeDistributed
from tensorflow.keras.optimizers import Adam

inputs = Input(shape=(MAX_LEN,))
x = Embedding(
    input_dim=voc_size,
    output_dim=128,
    mask_zero=True,
    trainable=True
)(inputs)

x = LSTM(128, return_sequences=True)(x)

outputs = TimeDistributed(
    Dense(Classes, activation="softmax")
)(x)

model_lstm = Model(inputs, outputs)

model_lstm.compile(
    optimizer=Adam(learning_rate=1e-3),
    loss="sparse_categorical_crossentropy",
    metrics=[masked_accuracy]
)

model_lstm.summary()

"""**Train the Model**"""

history_lstm = model_lstm.fit(
    X_train,
    Y_train,
    batch_size=64,
    epochs=100,
    validation_split=0.2
)

"""**Function to plot the model history**"""

import matplotlib.pyplot as plt

def plot_history(history, title):
    plt.figure(figsize=(12,4))

    plt.subplot(1,2,1)
    plt.plot(history.history['loss'], label='train')
    plt.plot(history.history.get('val_loss', []), label='val')
    plt.title(f'{title} - Loss')
    plt.xlabel('Epoch')
    plt.ylabel('Loss')
    plt.legend()
    plt.grid(True)

    plt.subplot(1,2,2)
    if 'masked_accuracy' in history.history:
        metric = 'masked_accuracy'
        val_metric = 'val_masked_accuracy'
    else:
        metric = 'accuracy'
        val_metric = 'val_accuracy'

    plt.plot(history.history[metric], label='train')
    plt.plot(history.history.get(val_metric, []), label='val')
    plt.title(f'{title} - Accuracy')
    plt.xlabel('Epoch')
    plt.ylabel(metric)
    plt.legend()
    plt.grid(True)

    plt.show()

plot_history(history_lstm,'LSTM')

"""لوحظ أثناء التدريب أن دقة التدريب كانت مرتفعة جدًا (98%) بينما كانت دقة التحقق منخفضة (17%)، مما يشير إلى مشكلة overfitting. هذا يعني أن النموذج تعلم بيانات التدريب بشكل ممتاز ولكنه لم يتمكن من التعميم على بيانات جديدة. الفارق الكبير بين train loss المنخفض وvalidation loss المرتفع يعكس أن النموذج يحفظ تفاصيل التدريب ولا يتعلم الأنماط العامة"""

y_pred = model_lstm.predict(X_test)

import numpy as np
y_pred_labels = np.argmax(y_pred, axis=-1)

y_true_flat = []
y_pred_flat = []

for true_seq, pred_seq in zip(Y_test, y_pred_labels):
    for t, p in zip(true_seq, pred_seq):
        if t != 0:      # تجاهل padding
            y_true_flat.append(t)
            y_pred_flat.append(p)

from sklearn.metrics import classification_report, f1_score

print(classification_report(
    y_true_flat,
    y_pred_flat,
    labels=[1,2,3,4,5,6],
    digits=4
))

macro_f1 = f1_score(
    y_true_flat,
    y_pred_flat,
    average="macro"
)

micro_f1 = f1_score(
    y_true_flat,
    y_pred_flat,
    average="micro"
)

print("Macro F1:", macro_f1)
print("Micro F1:", micro_f1)

"""حدثت مشكلة Overfitting في النموذج بسبب عدم توازن البيانات بين الفئات، إضافةً إلى أن نموذج LSTM أحادي الاتجاه يعتمد فقط على السياق السابق للكلمة ولا يأخذ السياق اللاحق بعين الاعتبار، وهو ما يجعله غير مناسب بشكل كافٍ لطبيعة هذه المشكلة اللغوية، مما أدى إلى ضعف التعميم على بيانات الاختبار.




"""

model_lstm.save("/content/drive/MyDrive/models/lstm_punct.h5")

model_lstm.evaluate(X_test,Y_test)

"""---

# 2.   Now using BiLSTM

شرح نموذج BiLSTM:

 يقوم بمعالجة التسلسل النصي في اتجاهين: من البداية إلى النهاية (Forward)
  ومن النهاية إلى البداية (Backward).
   هذا يسمح للنموذج بفهم السياق السابق واللاحق لكل كلمة داخل الجملة
"""

from tensorflow.keras.layers import Bidirectional
inputs = Input(shape=(MAX_LEN,))
x = Embedding(
    input_dim=voc_size,
    output_dim=128,
    mask_zero=True,
    trainable=True
)(inputs)

x = Bidirectional(
    LSTM(128, return_sequences=True)
)(x)

outputs = TimeDistributed(
    Dense(Classes, activation="softmax")
)(x)

model_bilstm = Model(inputs, outputs)

model_bilstm.compile(
    optimizer=Adam(learning_rate=1e-3),
    loss="sparse_categorical_crossentropy",
    metrics=[masked_accuracy]
)

model_bilstm.summary()

history_bilstm = model_bilstm.fit( X_train,
    Y_train,
    batch_size=64,
    epochs=100,
    validation_split=0.2
)

"""**Plot History**"""

plot_history(history_bilstm, "BiLSTM")

"""we get some improve by using BiLSTM that because it foucs on the before and after the word

but still the probelm of unbalanced data is on

لوحظ تحسن واضح في أداء التدريب عند استخدام BiLSTM مقارنةً بـ LSTM، ويعود ذلك إلى قدرة BiLSTM على استيعاب معلومات سياقية أشمل. في نموذج LSTM التقليدي، يتم تفسير الكلمة اعتمادًا فقط على الكلمات السابقة، مما قد يؤدي إلى فقدان معلومات مهمة تأتي لاحقًا في الجملة
"""

model_bilstm.save("/content/drive/MyDrive/models/bilstm_punct.h5")

y_pred = model_bilstm.predict(X_test)
y_pred_labels = np.argmax(y_pred, axis=-1)

y_true_flat = []
y_pred_flat = []

for true_seq, pred_seq in zip(Y_test, y_pred_labels):
    for t, p in zip(true_seq, pred_seq):
        if t != 0:
            y_true_flat.append(t)
            y_pred_flat.append(p)

from sklearn.metrics import classification_report, f1_score

print(classification_report(
    y_true_flat,
    y_pred_flat,
    labels=[1,2,3,4,5,6],
    digits=4
))

macro_f1 = f1_score(
    y_true_flat,
    y_pred_flat,
    average="macro"
)

micro_f1 = f1_score(
    y_true_flat,
    y_pred_flat,
    average="micro"
)

print("Macro F1:", macro_f1)
print("Micro F1:", micro_f1)

model_bilstm.evaluate(X_test,Y_test)

"""أظهرت النتائج أن نموذج BiLSTM يتفوق على نموذج LSTM في مهمة استعادة علامات الترقيم، وذلك بسبب قدرة BiLSTM على الاستفادة من السياق السابق واللاحق للكلمة في آنٍ واحد. وقد لوحظ تحسن ملحوظ في كل من Micro-F1 والدقة المقنّعة (Masked Accuracy)، في حين ظل Macro-F1 منخفضًا نسبيًا نتيجة عدم توازن البيانات وندرة بعض فئات علامات الترقيم.

# LET'S COMPARE
"""

import matplotlib.pyplot as plt
import numpy as np
models = ["LSTM", "BiLSTM"]

macro_f1 = [0.106, 0.266]
micro_f1 = [0.167, 0.598]
masked_acc = [0.17, 0.60]

x = np.arange(len(models))
width = 0.25

plt.figure(figsize=(8,5))
plt.bar(x - width, macro_f1, width, label="Macro F1")
plt.bar(x, micro_f1, width, label="Micro F1")
plt.bar(x + width, masked_acc, width, label="Masked Accuracy")

plt.xticks(x, models)
plt.ylabel("Score")
plt.title("LSTM vs BiLSTM Performance Comparison")
plt.legend()
plt.grid(axis="y", linestyle="--", alpha=0.6)
plt.show()

"""النتائج توضح تحسن عند استخدام BiLSTM من LSTM لكنه لازال غير كافاً للمشكلة

---

> # **تعاني مجموعة البيانات من عدم توازن بين الفئات، لذلك تم استخدام أوزان للفئات داخل دالة الخسارة (Weighted Loss) بهدف زيادة قيمة الخسارة عند الخطأ في تصنيف الفئات النادرة، مثل علامة الاستفهام (؟). يساعد ذلك النموذج على إعطاء اهتمام أكبر للفئات قليلة الظهور أثناء التدريب، مما يؤدي إلى تحسين أداء النموذج وقدرته على التعميم.**

أختيار الأوزان تم بكم مرة تكررت هذه الإشارة في البيانات وما مدى أهميتها ضمن النص
"""

import tensorflow as tf

class_weights = tf.constant([
    0.1,  # PAD
    1.0,  # .
    1.5,  # ،
    2.0,  # ؟
    2.0,  # !
    3.0,  # :
    3.0   # ؛
])

def weighted_loss(y_true, y_pred):
    y_true = tf.cast(y_true, tf.int32)
    loss = tf.keras.losses.sparse_categorical_crossentropy(
        y_true, y_pred
    )
    weights = tf.gather(class_weights, y_true)
    loss = loss * tf.cast(weights, tf.float32)
    return tf.reduce_sum(loss) / tf.reduce_sum(weights)

from tensorflow.keras.layers import Bidirectional
from tensorflow.keras.callbacks import EarlyStopping
inputs = Input(shape=(MAX_LEN,))
x = Embedding(
    input_dim=voc_size,
    output_dim=128,
    mask_zero=True,
    trainable=True
)(inputs)

x = Bidirectional(
    LSTM(128, return_sequences=True)
)(x)

outputs = TimeDistributed(
    Dense(Classes, activation="softmax")
)(x)

model_bilstm_weights = Model(inputs, outputs)

model_bilstm_weights.compile(
    optimizer=Adam(learning_rate=1e-3),
    loss=weighted_loss,
    metrics=[masked_accuracy]
)
early = EarlyStopping(
    monitor="val_loss",
    patience=3,
    restore_best_weights=True
)
model_bilstm_weights.summary()

history_bilstm_weights = model_bilstm_weights.fit( X_train,
    Y_train,
    batch_size=64,
    epochs=100,
    validation_split=0.2,
    callbacks=[early]
)

plot_history(history_bilstm_weights, "BiLSTM With Weights")

"""بهذه الطريقة تمكنا من منع overfitting وتمكنا من تحسين النموذج بشكل كبير"""

model_bilstm_weights.save("/content/drive/MyDrive/models/bilstm_weights_punct_tf.keras")

import numpy as np
y_pred = model_bilstm_weights.predict(X_test)
y_pred_labels = np.argmax(y_pred, axis=-1)

y_true_flat = []
y_pred_flat = []

for true_seq, pred_seq in zip(Y_test, y_pred_labels):
    for t, p in zip(true_seq, pred_seq):
        if t != 0:
            y_true_flat.append(t)
            y_pred_flat.append(p)

from sklearn.metrics import classification_report, f1_score

print(classification_report(
    y_true_flat,
    y_pred_flat,
    labels=[1,2,3,4,5,6],
    digits=4
))

macro_f1 = f1_score(
    y_true_flat,
    y_pred_flat,
    average="macro"
)

micro_f1 = f1_score(
    y_true_flat,
    y_pred_flat,
    average="micro"
)

print("Macro F1:", macro_f1)
print("Micro F1:", micro_f1)

model_bilstm_weights.evaluate(X_test,Y_test)

import matplotlib.pyplot as plt
import numpy as np
models = ["LSTM", "BiLSTM","BiLSTM_weight"]

macro_f1 = [0.106, 0.266,0.412]
micro_f1 = [0.167, 0.598,0.943]
masked_acc = [0.17, 0.60,0.9510]

x = np.arange(len(models))
width = 0.25

plt.figure(figsize=(8,5))
plt.bar(x - width, macro_f1, width, label="Macro F1")
plt.bar(x, micro_f1, width, label="Micro F1")
plt.bar(x + width, masked_acc, width, label="Masked Accuracy")

plt.xticks(x, models)
plt.ylabel("Score")
plt.title("LSTM vs BiLSTM vs BiLSTM with weights Performance Comparison")
plt.legend()
plt.grid(axis="y", linestyle="--", alpha=0.6)
plt.show()

"""عند دمج Weighted Loss مع نموذج BiLSTM، تحسن أداء النموذج بشكل أكبر، خاصة في حالة عدم توازن البيانات بين الفئات (Class Imbalance). تعمل الـ Weighted Loss على إعطاء وزن أكبر للفئات النادرة أثناء التدريب، مما يمنع النموذج من الانحياز للفئات الأكثر تكرارًا. هذا أدى إلى تعلم أكثر عدالة لجميع الفئات وتحسن ملحوظ في مقاييس التقييم مثل F-score مقارنة باستخدام BiLSTM بدون أوزان أو باستخدام LSTM التقليدي

that's clearly shows the benfits of wieghted loss in unbalanced stuation

---

> # It's clear that the BiLSTM with weighted loss is the Best Model

**Let's create a dictionary for it**
"""

macro_f1 = [0.106, 0.266,0.412]
micro_f1 = [0.167, 0.598,0.943]
masked_acc = [0.17, 0.60,0.9510]
lstm = {
    "number_step": 1,
    "name_model": "LSTM",
    "features": "Word embeddings",
    "parameters_model": "default",
    "methods_preprocessing": "tokenization + padding",
    "accuracy": 0.17,
    "F-score-macro": 0.106,
    "F-score-micro": 0.167
}
Bilstm = {
    "number_step": 1,
    "name_model": "BiLSTM",
    "features": "Word embeddings",
    "parameters_model": "default",
    "methods_preprocessing": "tokenization + padding",
    "accuracy": 0.60,
    "F-score-macro": 0.266,
    "F-score-micro": 0.598
}
bilstm_WL = {
    "number_step": 3,
    "name_model": "BiLSTM_weight",
    "features": "Word embeddings",
    "parameters_model": "class weights",
    "methods_preprocessing": "tokenization + padding",
    "accuracy": 0.9510,
    "F-score-macro": 0.412,
    "F-score-micro": 0.943
}
dictionary = []
dictionary.append(lstm)
dictionary.append(Bilstm)
dictionary.append(bilstm_WL)

"""

> # Pretrained Embeddings

"""

!pip install -qq gensim

"""helper functions

مجموعة توابع مساعدة بالتعامل مع البيانات
1 clean_chunk :
يقوم باخذ الكلمات ويعالجها بحيث تصبح اكثر ملائمة لموديل التضمين المدرب مسبقا بحيث يضمن توليد متجهات لمعظم الكلمات
فكلمة مثل "هدية" او "٥٠٠ مليون" ليس لها متجه مقابل لها بينما "هديه" و "500 مليون" يوجد لها
2 chunk_to_sentences:
  max_lenght يجمع الكلمات ضمن جمل لا يتجاوز طولها ال
  ('.','?','!')حيث يقسم الجمل حسب علامات الترقيم التي تظهر في نهاية الجملة

3 word2vec:
يعيد قيمة المتجه المقابل لكل كلمة حسب موديل الضمين المستخدم

4 sentence_to_vec:
يمر على كافة الكلمات في الجملة ويحولها لمتجهات

5 pad_batch:
labelيضيف حشو للكلمات وال
لتصبح كلها بنفس الطول

6 train_chunk:
ياخذ مجموعة بيانات وموديل التضمين المدرب مسبقا والشبكة
يعالج البيانات ويقسمها الى جمل ويحول كل كلمة فيها لمتجه ليهيئها للدخول للشبكة
يخلق وزن لكل label
ثم يبداء التدريب

7 test_chunk:
اخذ مجموعة بيانات وموديل التضمين المدرب مسبقا والشبكة
يعالج البيانات ويقسمها الى جمل ويحول كل كلمة فيها لمتجه ليهيئها للدخول للشبكة
ثم يتحقق منها على الشبكة المدربة

8 build_sample_weights:
يخلق وزن معين لكل label
يساعد بتدريب الشبكة بحيث لا يبدي اهمية للحشو وللفراغات كما لباقي علامات الترقيم
"""

PAD_LABEL = 7
END_LABELS = {1, 3, 4}
UNK_VECTOR = np.random.normal(
    scale=0.1,
    size=(300,)
).astype(np.float32)

arabic_to_eng = str.maketrans("٠١٢٣٤٥٦٧٨٩", "0123456789")

#تنظيف الكلمات وتهيئتها للاستخدام ضمن موديل التضمين المدرب مسبقا
def clean_chunk(df):

    s = df["word"].astype(str)

    s = s.str.strip()

    s = s.str.replace(r"[أإآ]", "ا", regex=True)
    s = s.str.replace("ة", "ه")
    s = s.str.replace("ى", "ي")
    s = s.str.replace(r"[()]", "", regex=True)


    s = s.str.translate(arabic_to_eng)

    df["word"] = s
    return df


# تجميع الكلمات ضمن جمل اما حسب نهاية الجملة او حسب طول الجمل اذا تم تحديده
def chunk_to_sentences(df, end_labels = END_LABELS, max_lenght=100):
    sentences = []
    sentence_labels = []

    current_words = []
    current_labels = []

    for word, label in zip(df["word"], df["label_id"]):
        current_words.append(word)
        current_labels.append(label)

        if max_lenght:
          if label in end_labels or len(current_words)>= max_lenght:
              sentences.append(current_words)
              sentence_labels.append(current_labels)

              current_words = []
              current_labels = []
        else:
          if label in end_labels:
              sentences.append(current_words)
              sentence_labels.append(current_labels)

              current_words = []
              current_labels = []

    if current_words:
        sentences.append(current_words)
        sentence_labels.append(current_labels)

    return sentences, sentence_labels

# تحويل كلمة لمتجه
def word2vec(word, model):
    if word in model.wv:
      return model.wv[word]
    return UNK_VECTOR

# تحويل كلمات جملة لمتجه
def sentence_to_vec(sentence, model):
    return np.array(
        [word2vec(w, model) for w in sentence],
        dtype=np.float32
    )


def pad_batch(X, y, pad_label):
    X_pad = tf.keras.preprocessing.sequence.pad_sequences(
        X,
        padding="post",
        dtype="float32"
    )

    y_pad = tf.keras.preprocessing.sequence.pad_sequences(
        y,
        padding="post",
        value=pad_label
    )

    return X_pad, y_pad

#تدريب الشبكة على قسم من البيانات
def train_chunk(chunk,em_model,model):
  chunk = clean_chunk(chunk)
  sentences, labels = chunk_to_sentences(chunk)
  sentences = [sentence_to_vec(s, em_model) for s in sentences]
  sentences, labels = pad_batch(sentences, labels, PAD_LABEL)

  sample_weights = build_sample_weights(labels, label_weights)

  model.fit(
        sentences, #X_pad
        labels, #y_pad
        epochs=3,
        sample_weight=sample_weights,
        batch_size=16,
        validation_split=0.2
    )

def test_chunk(chunk,em_model,model):
    chunk = clean_chunk(chunk)
    sentences, labels = chunk_to_sentences(chunk)
    sentences = [sentence_to_vec(s, em_model) for s in sentences]
    sentences, labels = pad_batch(sentences, labels, PAD_LABEL)

    # تقييم
    return model.evaluate(
        sentences, #X_pad
        labels, #y_pad
        verbose=0
    )


label_weights = {
    0: 0.2,   # لا ترقيم (الأكثر شيوعًا)
    1: 2.0,   # .
    2: 2.0,   # ,
    3: 2.5,
    4: 2.5,
    5: 2.5,
    6: 2.5,
    7: 2.5,
    PAD_LABEL: 0.0
}

def build_sample_weights(y, label_weights):

    weights = np.zeros_like(y, dtype=np.float32)

    for label, w in label_weights.items():
        weights[y == label] = w

    return weights

import tensorflow as tf
def masked_accuracy(y_true, y_pred):
    y_pred = tf.argmax(y_pred, axis=-1, output_type=tf.int64)
    y_true = tf.cast(y_true, tf.int64)

    mask = tf.not_equal(y_true, PAD_LABEL)

    matches = tf.equal(y_true, y_pred)
    matches = tf.logical_and(mask, matches)

    return tf.reduce_sum(tf.cast(matches, tf.float32)) / (
        tf.reduce_sum(tf.cast(mask, tf.float32)) + 1e-9
    )

def masked_f1_micro(y_true, y_pred):
    # توقعات النموذج
    y_pred = tf.argmax(y_pred, axis=-1, output_type=tf.int64)
    y_true = tf.cast(y_true, tf.int64)

    # تجاهل padding
    mask = tf.not_equal(y_true, PAD_LABEL)

    y_true = tf.boolean_mask(y_true, mask)
    y_pred = tf.boolean_mask(y_pred, mask)

    # True Positives
    tp = tf.reduce_sum(
        tf.cast(tf.equal(y_true, y_pred), tf.float32)
    )

    # Micro F1
    precision = tp / (tf.cast(tf.size(y_pred), tf.float32) + 1e-9)
    recall    = tp / (tf.cast(tf.size(y_true), tf.float32) + 1e-9)

    f1 = 2 * precision * recall / (precision + recall + 1e-9)
    return f1

"""##Word2Vec

load data
"""

CHUNK_SIZE = 50000
PATH = "/tmp/dataset.csv"

df = pd.read_csv(
    PATH,
    chunksize=CHUNK_SIZE,
    usecols=["word", "label_id"],
    encoding="utf-8"
)
total_rows = 308639623

"""**load embedding model**"""

!pip install -qq gensim
!wget -qq -c https://bakrianoo.ewr1.vultrobjects.com/aravec/full_grams_cbow_300_twitter.zip
!unzip -qq /content/full_grams_cbow_300_twitter.zip -d /content/embedding_model

"""# CBOW"""

import gensim
twt_cbow = gensim.models.Word2Vec.load('/content/embedding_model/full_grams_cbow_300_twitter.mdl')

!wget -qq -c https://bakrianoo.ewr1.vultrobjects.com/aravec/full_grams_sg_300_twitter.zip
!unzip -qq /content/full_grams_sg_300_twitter.zip -d /content/embedding_model

"""**Model for train**

تهيئة الشبكة
لم يتم تعقيد الشبكة لانه سيتم تدريبها كل مرة عل قسم من البيانات ومن اجل تقليل التعلم الزائد لانها لم تدرب على كافة البانات دفعة واحدة
دخل الشبكة هو sequence
من الكلمات بعد تحويلها لمتجهات طول كل متجه 300
وخرجها هو sequence
مجموعة من ال labels
"""

MAX_LEN = 100
PAD_LABEL = 7
NUM_LABELS = 8     # علامات ترقيم + الحشو

embedding_dim = 300

loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(
    from_logits=False,
    reduction="none"
)

model = tf.keras.Sequential()
model.add(
    tf.keras.layers.Input(
        shape=(MAX_LEN, embedding_dim)
    )
)
model.add(tf.keras.layers.Bidirectional(
            tf.keras.layers.LSTM(
              128,
              return_sequences=True
          )
    )
)

model.add(
    tf.keras.layers.Dense(
        NUM_LABELS,
        activation="softmax"
    )
)


model.summary()

# OUTPUT:
# Model: "sequential_11"
# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
# ┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
# ┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
# │ bidirectional_11                │ (None, 100, 256)       │       439,296 │
# │ (Bidirectional)                 │                        │               │
# ├─────────────────────────────────┼────────────────────────┼───────────────┤
# │ dense_11 (Dense)                │ (None, 100, 8)         │         2,056 │
# └─────────────────────────────────┴────────────────────────┴───────────────┘
#  Total params: 441,352 (1.68 MB)
#  Trainable params: 441,352 (1.68 MB)
#  Non-trainable params: 0 (0.00 B)

model.compile(
    optimizer=tf.keras.optimizers.Adam(1e-3),
    loss="sparse_categorical_crossentropy",
    metrics=[masked_accuracy,masked_f1_micro]
)

"""# try train for CBOW embedding model

نظرة لحجم الداتة سيتم اخذ كل مرة قسم والتدريب عليه على حدا
سيتم اعتماد 100 chunk
اي ما يقارب 5000000 كلمة
حيث كل chunk يحوي 50000
سيتم التدريب بعد تحويل الكلمات لمتجهات
CBOWباستعمل موديل تضمين جاهز درب بطريقة
"""

num_chunk_for_model = 100
num_chunk_to_train = math.ceil(num_chunk_for_model*0.8)
num_chunk_to_test =  num_chunk_for_model - num_chunk_to_train


for i, chunk in enumerate(df):
  if i == num_chunk_to_train:
      break
  print(f"train for {i} chunk")
  train_chunk(chunk,twt_cbow,model)

# ONLY LAST CHUNK OUTPUT
# train for 79 chunk
# Epoch 1/3
# 93/93 ━━━━━━━━━━━━━━━━━━━━ 2s 18ms/step - loss: 0.0246 - masked_accuracy: 0.9289 - masked_f1_micro: 0.9289 - val_loss: 0.0302 - val_masked_accuracy: 0.9178 - val_masked_f1_micro: 0.9178
# Epoch 2/3
# 93/93 ━━━━━━━━━━━━━━━━━━━━ 2s 17ms/step - loss: 0.0135 - masked_accuracy: 0.9497 - masked_f1_micro: 0.9497 - val_loss: 0.0306 - val_masked_accuracy: 0.9298 - val_masked_f1_micro: 0.9298
# Epoch 3/3
# 93/93 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0093 - masked_accuracy: 0.9618 - masked_f1_micro: 0.9618 - val_loss: 0.0325 - val_masked_accuracy: 0.9311 - val_masked_f1_micro: 0.9311

"""**test on last training chunk (test model in trained data)**"""

Loss,Accuracy,F1 = test_chunk(chunk,twt_sg,model)
print("===== Train RESULTS =====")
print("Loss:", Loss)
print("Accuracy:",  Accuracy)
print("F1:",  F1)

# OUTPUT:
# ===== Train RESULTS =====
# Loss: 14.413317680358887
# Accuracy: 0.9411631226539612
# F1: 0.9411631226539612

test_results = []

for i, chunk in enumerate(df):
    if i == num_chunk_to_test:
      break
    # print(f"test on chunk {i}")
    res = test_chunk(chunk,twt_sg,model)
    test_results.append(res)


import numpy as np

test_results = np.array(test_results)

mean_loss = test_results[:, 0].mean()
mean_acc  = test_results[:, 1].mean()
mean_f1   = test_results[:, 2].mean()

print("===== TEST RESULTS =====")
print("Loss:", mean_loss)
print("Accuracy:", mean_acc)
print("F1:", mean_f1)

#OUTPUT:
# ===== TEST RESULTS =====
# Loss: 14.45023055076599
# Accuracy: 0.92779061794281
# F1: 0.92779061794281

"""# try train for skip_gram embedding model

سيتم التدريب بعد تحويل الكلمات لمتجهات
Skip-gram موديل تضمين جاهز درب بطريقة
"""

twt_sg = gensim.models.Word2Vec.load('/content/embedding_model/full_grams_sg_300_twitter.mdl')

"""# try train for skip_gram embedding model"""

num_chunk_for_model = 100
num_chunk_to_train = math.ceil(num_chunk_for_model*0.8)
num_chunk_to_test =  num_chunk_for_model - num_chunk_to_train


for i, chunk in enumerate(df):
  if i == num_chunk_to_train:
      break
  print(f"train for {i} chunk")
  train_chunk(chunk,twt_sg,model)
# ONLY LAST CHUNK OUTPUT
# train for 79 chunk
# Epoch 1/3
# 93/93 ━━━━━━━━━━━━━━━━━━━━ 2s 18ms/step - loss: 0.0246 - masked_accuracy: 0.9289 - masked_f1_micro: 0.9289 - val_loss: 0.0302 - val_masked_accuracy: 0.9178 - val_masked_f1_micro: 0.9178
# Epoch 2/3
# 93/93 ━━━━━━━━━━━━━━━━━━━━ 2s 17ms/step - loss: 0.0135 - masked_accuracy: 0.9497 - masked_f1_micro: 0.9497 - val_loss: 0.0306 - val_masked_accuracy: 0.9298 - val_masked_f1_micro: 0.9298
# Epoch 3/3
# 93/93 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0093 - masked_accuracy: 0.9618 - masked_f1_micro: 0.9618 - val_loss: 0.0325 - val_masked_accuracy: 0.9311 - val_masked_f1_micro: 0.9311

"""**test on last training chunk (test model in trained data)**"""

Loss,Accuracy,F1 = test_chunk(chunk,twt_sg,model)
print("===== Train RESULTS =====")
print("Loss:", Loss)
print("Accuracy:",  Accuracy)
print("F1:",  F1)
# OUTPUT:
# ===== Train RESULTS =====
# Loss: 7.803508281707764
# Accuracy: 0.9341473579406738
# F1: 0.9341473579406738

"""**Test on testdata**"""

test_results = []

for i, chunk in enumerate(df):
    if i == num_chunk_to_test:
      break
    # print(f"test on chunk {i}")
    res = test_chunk(chunk,twt_sg,model)
    test_results.append(res)


import numpy as np

test_results = np.array(test_results)

mean_loss = test_results[:, 0].mean()
mean_acc  = test_results[:, 1].mean()
mean_f1   = test_results[:, 2].mean()

print("===== TEST RESULTS =====")
print("Loss:", mean_loss)
print("Accuracy:", mean_acc)
print("F1:", mean_f1)

# OUTPUT:
# ===== TEST RESULTS =====
# Loss: 7.760844326019287
# Accuracy: 0.9235462754964828
# F1: 0.9235462695360184

"""**Compare between the two models**"""

import matplotlib.pyplot as plt
import numpy as np
models = ["CBOW", "Skip_Gram"]
# Accuracy: 0.92779061794281
# F1: 0.92779061794281
micro_f1 = [0.927, 0.923]
masked_acc = [0.927,0.923]

x = np.arange(len(models))
width = 0.25

plt.figure(figsize=(8,5))
# plt.bar(x - width, macro_f1, width, label="Macro F1")
plt.bar(x, micro_f1, width, label="Micro F1")
plt.bar(x + width, masked_acc, width, label="Masked Accuracy")

plt.xticks(x, models)
plt.ylabel("Score")
plt.title("CBOW word2vec vs Skip_Gram")
plt.legend()
plt.grid(axis="y", linestyle="--", alpha=0.6)
plt.show()

"""Very similre accuracy"""

CBOW = {
    "number_step": 4,
    "name_model": "word2vec_CBOW",
    "features": "pretrain embeddings",
    "parameters_model": "class weights",
    "methods_preprocessing": "tokenization + padding",
    "accuracy": 0.927,
    "F-score-macro": 0.927,
    "F-score-micro": None
}
Skip_Gram = {
    "number_step": 5,
    "name_model": "word2vec_Skip_Gram",
    "features": "pretrain embeddings",
    "parameters_model": "class weights",
    "methods_preprocessing": "tokenization + padding",
    "accuracy": 0.923,
    "F-score-macro": 0.923,
    "F-score-micro": None
}
dictionary.append(CBOW)
dictionary.append(Skip_Gram)

"""

># Transfer Learning

"""

!pip install transformers datasets seqeval

!pip install --upgrade pandas

!pip install -q gdown transformers torch datasets accelerate scikit-learn pandas

"""تحميل ملف البيانات وقراءته على أجزاء (chunks) لتوفير الذاكرة.

"""

import pandas as pd
import gdown

url = "https://drive.google.com/uc?id=1sQppeJ4RMzuUmwaZFe7Xfa2q8kiImWR6"
dataset_path = "/tmp/dataset.csv"

gdown.download(url, dataset_path, quiet=False)

chunks = pd.read_csv(dataset_path, chunksize=200000)

chunk = next(chunks)
chunk.sample(10)

"""استخراج الكلمات والوسوم"""

X = chunk["word"].tolist()
Y = chunk["label_id"].tolist()

for i in range(10):
    print(X[i], "->", Y[i])

""" تقسيم الكلمات إلى جمل"""

def sequence(words, labels):
    X, Y = [], []
    sent, sent_labels = [], []

    for word, label in zip(words, labels):
        sent.append(word)
        sent_labels.append(label)

        if label in [1, 3, 4]:  # . ؟ !
            X.append(sent)
            Y.append(sent_labels)
            sent, sent_labels = [], []

    if len(sent) > 0:
        X.append(sent)
        Y.append(sent_labels)

    return X, Y

X, Y = sequence(X, Y)

print(X[0])
print(Y[0])

clean_X, clean_Y = [], []

for sent, labels in zip(X, Y):
    new_sent, new_labels = [], []

    for w, l in zip(sent, labels):
        if isinstance(w, str) and w.strip() != "":
            new_sent.append(w)
            new_labels.append(l)

    if len(new_sent) > 0:
        clean_X.append(new_sent)
        clean_Y.append(new_labels)

print("Deleted samples:", len(X) - len(clean_X))

X = clean_X
Y = clean_Y

"""> # Load araBERT model

AraBERT هو نموذج لغوي عميق مبني على بنية BERT (Bidirectional Encoder Representations from Transformers)، لكنه مُدرَّب خصيصًا على اللغة العربية. يهدف إلى فهم النص العربي بدقة أعلى من النماذج العامة، وذلك لأنه أُعيد تصميمه ليتعامل مع خصائص العربية مثل الصرف الغني، وتعدد الصيغ، واختلاف اللهجات، وعلامات التشكيل.
"""

import torch
from transformers import AutoTokenizer, AutoModelForTokenClassification

MODEL_NAME = "aubmindlab/bert-base-arabertv02"

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
model = AutoModelForTokenClassification.from_pretrained(
    MODEL_NAME,
    num_labels=7
)

"""**Prepare the data for the model**"""

def encode_sentence(words, labels, max_len=64):
    encoding = tokenizer(
        words,
        is_split_into_words=True,
        truncation=True,
        padding="max_length",
        max_length=max_len,
        return_tensors="pt"
    )

    word_ids = encoding.word_ids()
    label_ids = []
    previous_word_idx = None

    for word_idx in word_ids:
        if word_idx is None:
            label_ids.append(-100)
        elif word_idx != previous_word_idx:
            label_ids.append(labels[word_idx])
        else:
            label_ids.append(-100)
        previous_word_idx = word_idx

    encoding["labels"] = torch.tensor(label_ids)
    return encoding

encoded_data = []
# max_len = max(len(s) for s in X)
for sent, lab in zip(X, Y):
    encoded_data.append(encode_sentence(sent, lab,max_len=128))

from sklearn.model_selection import train_test_split

train_data, val_data = train_test_split(
    encoded_data,
    test_size=0.2,
    random_state=42
)

"""إنشاء Dataset خاص بـ PyTorch"""

class PunctuationDataset(torch.utils.data.Dataset):
    def __init__(self, data):
        self.data = data

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        return {k: v.squeeze(0) for k, v in self.data[idx].items()}

train_dataset = PunctuationDataset(train_data)
val_dataset   = PunctuationDataset(val_data)

"""**Function to compute accuracy with ignoring (-100) padding and compute the F1 score**"""

import numpy as np
from sklearn.metrics import accuracy_score, f1_score

def compute_metrics(eval_pred):
    logits = eval_pred.predictions
    labels =  eval_pred.label_ids
    predictions = np.argmax(logits, axis=-1)

    true_labels = []
    true_preds  = []

    for pred_seq, label_seq in zip(predictions, labels):
        for p, l in zip(pred_seq, label_seq):
            if l != -100:  # تجاهل padding و subwords
                true_labels.append(l)
                true_preds.append(p)

    accuracy = accuracy_score(true_labels, true_preds)
    micro_f1 = f1_score(true_labels, true_preds, average="micro")
    macro_f1 = f1_score(true_labels, true_preds, average="macro")

    return {
        "accuracy": accuracy,
        "micro_f1": micro_f1,
        "macro_f1": macro_f1
    }

"""**Train the Model**"""

from transformers import Trainer, TrainingArguments

training_args = TrainingArguments(
    output_dir="./results",
    eval_strategy="epoch",
    save_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    num_train_epochs=5,
    weight_decay=0.01,
    logging_steps=100,
    load_best_model_at_end=True,
    metric_for_best_model="eval_macro_f1",
    greater_is_better=True,
    report_to="none"
)

from transformers import EarlyStoppingCallback

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    tokenizer=tokenizer,
    compute_metrics=compute_metrics,
    callbacks=[EarlyStoppingCallback(early_stopping_patience=2)]
)

trainer.train()

"""بشكل عام تشير هذه النتائج إلى أن النموذج تعلّم المهمة بكفاءة مع أفضل توازن بين الأداء والتعميم يتحقق في epoch الأولى بينما تتطلب epoch المتأخرة تقنيات إضافية مثل التوقف المبكر (Early Stopping) أو تنظيم النموذج (Regularization) للحد من فرط التعلّم"""

preds = trainer.predict(val_dataset)
compute_metrics(preds)

"""**Plot the training curve**"""

import matplotlib.pyplot as plt
logs = trainer.state.log_history
df = pd.DataFrame(logs)

train_loss = df[df["loss"].notna()][["epoch", "loss"]]
val_loss   = df[df["eval_loss"].notna()][["epoch", "eval_loss"]]

plt.figure(figsize=(8,5))

plt.plot(train_loss["epoch"], train_loss["loss"], label="Train Loss (No FT)")
plt.plot(val_loss["epoch"], val_loss["eval_loss"], label="Val Loss (No FT)")



plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.title("Training vs Validation Loss")
plt.legend()
plt.grid(True)
plt.show()

metrics = df[df["eval_accuracy"].notna()][
    ["epoch", "eval_accuracy", "eval_micro_f1", "eval_macro_f1"]
]

plt.figure(figsize=(8,5))

plt.plot(metrics["epoch"], metrics["eval_macro_f1"], label="eval_macro_f1 (No FT)")

plt.xlabel("Epoch")
plt.ylabel("macro f1")
plt.title("Validation macro f1")
plt.legend()
plt.grid(True)
plt.show()

plt.figure(figsize=(8,5))

plt.plot(metrics["epoch"], metrics["eval_micro_f1"], label="eval micro f1 (No FT)")

plt.xlabel("Epoch")
plt.ylabel("micro f1")
plt.title("Validation micro f1")
plt.legend()
plt.grid(True)
plt.show()

label_map = {
    0: "",
    1: ".",
    2: "،",
    3: "؟",
    4: "!",
    5: ":",
    6: "؛"
}

"""تجربة النموذج على جملة جديدة"""

def predict_punctuation(words):
    encoding = tokenizer(
        words,
        is_split_into_words=True,
        return_tensors="pt"
    )

    with torch.no_grad():
        outputs = model(**encoding)

    preds = torch.argmax(outputs.logits, dim=-1)[0].tolist()
    word_ids = encoding.word_ids()

    result = []
    used = set()

    for i, word_id in enumerate(word_ids):
        if word_id is not None and word_id not in used:
            used.add(word_id)
            result.append(words[word_id] + label_map[preds[i]])

    return " ".join(result)

test_sentence = ["أكل", "الولد", "الخبز", "وشرب", "الماء"]
print(predict_punctuation(test_sentence))

"""

> # Now train with fine-tuning

"""

model_with_FN = AutoModelForTokenClassification.from_pretrained(
    MODEL_NAME,
    num_labels=7
)

"""*First freez the embedding gradens*"""

for param in model_with_FN.bert.embeddings.parameters():
    param.requires_grad = False

from transformers import Trainer, TrainingArguments

training_args = TrainingArguments(
    output_dir="./results",
    eval_strategy="epoch",
    save_strategy="epoch",
    learning_rate=5e-5,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    num_train_epochs=5,
    weight_decay=0.01,
    logging_steps=100,
    load_best_model_at_end=True,
    metric_for_best_model="eval_macro_f1",
    greater_is_better=True,
    report_to="none",
    fp16 = True
)

"""**Train the Model while the layers are freezed**"""

from transformers import EarlyStoppingCallback

trainer = Trainer(
    model=model_with_FN,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    tokenizer=tokenizer,
    compute_metrics=compute_metrics,
    callbacks=[EarlyStoppingCallback(early_stopping_patience=2)]

)

trainer.train()

"""*Unfreeze the embedding layers*"""

for param in model_with_FN.bert.embeddings.parameters():
    param.requires_grad = True

from transformers import Trainer, TrainingArguments

training_args = TrainingArguments(
    output_dir="./results",
    eval_strategy="epoch",
    save_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    num_train_epochs=5,
    weight_decay=0.01,
    logging_steps=100,
    load_best_model_at_end=True,
    metric_for_best_model="eval_macro_f1",
    greater_is_better=True,
    report_to="none",
    # fp16 = True
)

"""**Now trin the full model**"""

from transformers import EarlyStoppingCallback

trainer = Trainer(
    model=model_with_FN,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    tokenizer=tokenizer,
    compute_metrics=compute_metrics,
        callbacks=[EarlyStoppingCallback(early_stopping_patience=2)]

)

trainer.train()

preds = trainer.predict(val_dataset)
compute_metrics(preds)

"""**Plot the training curve**"""

import matplotlib.pyplot as plt
logs = trainer.state.log_history
df = pd.DataFrame(logs)

train_loss = df[df["loss"].notna()][["epoch", "loss"]]
val_loss   = df[df["eval_loss"].notna()][["epoch", "eval_loss"]]

plt.figure(figsize=(8,5))

plt.plot(train_loss["epoch"], train_loss["loss"], label="Train Loss (with FT)")
plt.plot(val_loss["epoch"], val_loss["eval_loss"], label="Val Loss (with FT)")



plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.title("Training vs Validation Loss")
plt.legend()
plt.grid(True)
plt.show()

metrics = df[df["eval_accuracy"].notna()][
    ["epoch", "eval_accuracy", "eval_micro_f1", "eval_macro_f1"]
]

plt.figure(figsize=(8,5))

plt.plot(metrics["epoch"], metrics["eval_macro_f1"], label="eval_macro_f1 (with FT)")

plt.xlabel("Epoch")
plt.ylabel("macro f1")
plt.title("Validation macro f1")
plt.legend()
plt.grid(True)
plt.show()

plt.figure(figsize=(8,5))

plt.plot(metrics["epoch"], metrics["eval_micro_f1"], label="eval micro f1 (with FT)")

plt.xlabel("Epoch")
plt.ylabel("micro f1")
plt.title("Validation micro f1")
plt.legend()
plt.grid(True)
plt.show()

from transformers import AutoModelForTokenClassification, AutoTokenizer

path = "/content/drive/MyDrive/arabert_finetuned_model_F"

model_with_FN.save_pretrained(path)
tokenizer.save_pretrained(path)

"""# **Compare between the model without fine-tuning and with fine-tuining**"""

import matplotlib.pyplot as plt
import numpy as np
models = ["araBERT", "araBERT - Fine-tuning"]
# {'accuracy': 0.9677516576250753,
#  'micro_f1': 0.9677516576250753,
#  'macro_f1': 0.6217795752709856}
#  {'accuracy': 0.9678018886879647,
#  'micro_f1': 0.9678018886879647,
#  'macro_f1': 0.6181109132886856}
# {'accuracy': 0.9681032750653004,
#  'micro_f1': 0.9681032750653004,
#  'macro_f1': 0.6223478009223045}
macro_f1 = [0.621, 0.622]
micro_f1 = [0.967, 0.968]
masked_acc = [0.967,0.968]

x = np.arange(len(models))
width = 0.25

plt.figure(figsize=(8,5))
plt.bar(x - width, macro_f1, width, label="Macro F1")
plt.bar(x, micro_f1, width, label="Micro F1")
plt.bar(x + width, masked_acc, width, label="Masked Accuracy")

plt.xticks(x, models)
plt.ylabel("Score")
plt.title("normal araBERT vs araBERT Fine-tuning Performance Comparison")
plt.legend()
plt.grid(axis="y", linestyle="--", alpha=0.6)
plt.show()

"""على الرغم من استخدام fine-tuning إلا أن النموذج لم يتحسن كثيراً وهذا يدل على قوة نموذج araBERT في التعامل مع اللغة العربية

> # We will use the Fine-tuning model but adding weighted loss

مع استخدام weighted loss نجبر النموذج على الأهتمام بإشارات الأقل تكراراً وبذلك نحسن الأداء ونتغلب على مشكلة Unbalanced dataset
"""

import pandas as pd
import gdown

url = "https://drive.google.com/uc?id=1sQppeJ4RMzuUmwaZFe7Xfa2q8kiImWR6"
dataset_path = "/tmp/dataset.csv"

gdown.download(url, dataset_path, quiet=False)

chunks_new = pd.read_csv(dataset_path, skiprows=range(1, 200001), chunksize=200000)

chunks_new = next(chunks_new)
chunks_new.sample(10)

X = chunks_new["word"].tolist()
Y = chunks_new["label_id"].tolist()

for i in range(10):
    print(X[i], "->", Y[i])

def sequence(words, labels):
    X, Y = [], []
    sent, sent_labels = [], []

    for word, label in zip(words, labels):
        sent.append(word)
        sent_labels.append(label)

        if label in [1, 3, 4]:  # . ؟ !
            X.append(sent)
            Y.append(sent_labels)
            sent, sent_labels = [], []

    if len(sent) > 0:
        X.append(sent)
        Y.append(sent_labels)

    return X, Y

X, Y = sequence(X, Y)

print(X[0])
print(Y[0])

clean_X, clean_Y = [], []

for sent, labels in zip(X, Y):
    new_sent, new_labels = [], []

    for w, l in zip(sent, labels):
        if isinstance(w, str) and w.strip() != "":
            new_sent.append(w)
            new_labels.append(l)

    if len(new_sent) > 0:
        clean_X.append(new_sent)
        clean_Y.append(new_labels)

print("Deleted samples:", len(X) - len(clean_X))

X = clean_X
Y = clean_Y

def encode_sentence(words, labels, max_len=64):
    encoding = tokenizer(
        words,
        is_split_into_words=True,
        truncation=True,
        padding="max_length",
        max_length=max_len,
        return_tensors="pt"
    )

    word_ids = encoding.word_ids()
    label_ids = []
    previous_word_idx = None

    for word_idx in word_ids:
        if word_idx is None:
            label_ids.append(-100)
        elif word_idx != previous_word_idx:
            label_ids.append(labels[word_idx])
        else:
            label_ids.append(-100)
        previous_word_idx = word_idx

    encoding["labels"] = torch.tensor(label_ids)
    return encoding

encoded_data = []
# max_len = max(len(s) for s in X)
for sent, lab in zip(X, Y):
    encoded_data.append(encode_sentence(sent, lab,max_len=128))

from sklearn.model_selection import train_test_split

train_data, val_data = train_test_split(
    encoded_data,
    test_size=0.1,
    random_state=42
)

class PunctuationDataset(torch.utils.data.Dataset):
    def __init__(self, data):
        self.data = data

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        return {k: v.squeeze(0) for k, v in self.data[idx].items()}

train_dataset = PunctuationDataset(train_data)
val_dataset   = PunctuationDataset(val_data)

"""# **Weighted Trainer for weighted loss**"""

import torch
import torch.nn.functional as F
from transformers import Trainer

class_weights = torch.tensor([0.1, 1.0, 1.3, 3.0, 2.5, 3.2, 3.5], dtype=torch.float)

class WeightedTrainer(Trainer):
    def compute_loss(self, model, inputs, return_outputs=False, **kwargs):
        labels = inputs.pop("labels")
        outputs = model(**inputs)
        logits = outputs.logits

        loss = F.cross_entropy(
            logits.view(-1, model.config.num_labels),
            labels.view(-1),
            weight=class_weights.to(logits.device),
            ignore_index=-100
        )

        return (loss, outputs) if return_outputs else loss

from transformers import Trainer, TrainingArguments

training_args = TrainingArguments(
    output_dir="./results",
    eval_strategy="epoch",
    save_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    num_train_epochs=5,
    weight_decay=0.01,
    logging_steps=100,
    load_best_model_at_end=True,
    metric_for_best_model="macro_f1",
    greater_is_better=True,
    report_to="none",
    fp16 = True
)

from transformers import EarlyStoppingCallback

trainer = WeightedTrainer(
    model=model_with_FN,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    tokenizer=tokenizer,
    compute_metrics=compute_metrics,
        callbacks=[EarlyStoppingCallback(early_stopping_patience=2)]

)

trainer.train()

preds = trainer.predict(val_dataset)
compute_metrics(preds)

import matplotlib.pyplot as plt
logs = trainer.state.log_history
df = pd.DataFrame(logs)

train_loss = df[df["loss"].notna()][["epoch", "loss"]]
val_loss   = df[df["eval_loss"].notna()][["epoch", "eval_loss"]]

plt.figure(figsize=(8,5))

plt.plot(train_loss["epoch"], train_loss["loss"], label="Train Loss (with FT)")
plt.plot(val_loss["epoch"], val_loss["eval_loss"], label="Val Loss (with FT)")



plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.title("Training vs Validation Loss")
plt.legend()
plt.grid(True)
plt.show()

metrics = df[df["eval_accuracy"].notna()][
    ["epoch", "eval_accuracy", "eval_micro_f1", "eval_macro_f1"]
]

plt.figure(figsize=(8,5))

plt.plot(metrics["epoch"], metrics["eval_macro_f1"], label="eval_macro_f1 (with FT)")

plt.xlabel("Epoch")
plt.ylabel("macro f1")
plt.title("Validation macro f1")
plt.legend()
plt.grid(True)
plt.show()

plt.figure(figsize=(8,5))

plt.plot(metrics["epoch"], metrics["eval_micro_f1"], label="eval micro f1 (with FT)")

plt.xlabel("Epoch")
plt.ylabel("micro f1")
plt.title("Validation micro f1")
plt.legend()
plt.grid(True)
plt.show()

# trainer.save_model("/content/drive/MyDrive/arabert_weighted")
from transformers import AutoModelForTokenClassification, AutoTokenizer

path = "/content/drive/MyDrive/arabert_finetuned_model_wieghtedLoss"

model_with_FN.save_pretrained(path)
tokenizer.save_pretrained(path)

"""# **Compare between the model without fine-tuning and with fine-tuining and fine-tuining with weighed loss**"""

import matplotlib.pyplot as plt
import numpy as np
models = ["araBERT", "araBERT - Fine-tuning","Fine-tuning with WL"]
# {'accuracy': 0.9677516576250753,
#  'micro_f1': 0.9677516576250753,
#  'macro_f1': 0.6217795752709856}
#  {'accuracy': 0.9678018886879647,
#  'micro_f1': 0.9678018886879647,
#  'macro_f1': 0.6181109132886856}
# {'accuracy': 0.9681032750653004,
#  'micro_f1': 0.9681032750653004,
#  'macro_f1': 0.6223478009223045}
# {'accuracy': 0.9699874292897549,
#  'micro_f1': 0.9699874292897549,
#  'macro_f1': 0.8775410851751663}
macro_f1 = [0.621, 0.622,0.877]
micro_f1 = [0.967, 0.968,0.969]
masked_acc = [0.967,0.968,0.969]

x = np.arange(len(models))
width = 0.25

plt.figure(figsize=(8,5))
plt.bar(x - width, macro_f1, width, label="Macro F1")
plt.bar(x, micro_f1, width, label="Micro F1")
plt.bar(x + width, masked_acc, width, label="Masked Accuracy")

plt.xticks(x, models)
plt.ylabel("Score")
plt.title("normal araBERT vs araBERT Fine-tuning Performance Comparison")
plt.legend()
plt.grid(axis="y", linestyle="--", alpha=0.6)
plt.show()

"""نلاحظ تحسن جيد إلى حد كبير في F1-macro بعد استخدام weighted loss"""

models = ["araBERT", "araBERT - Fine-tuning","Fine-tuning with WL"]
macro_f1 = [0.621, 0.622,0.877]
micro_f1 = [0.967, 0.968,0.969]
masked_acc = [0.967,0.968,0.969]
araBERT_base = {
    "number_step": 6,
    "name_model": "araBERT",
    "features": "Contextual subword embeddings",
    "parameters_model": "default",
    "methods_preprocessing": "tokenization + padding",
    "accuracy": 0.967,
    "F-score-macro": 0.621,
    "F-score-micro": 0.967
}
araBERT_ft = {
    "number_step": 7,
    "name_model": "araBERT - Fine-tuning",
    "features": "Contextual subword embeddings",
    "parameters_model": "Fine-tuning",
    "methods_preprocessing": "tokenization + padding",
    "accuracy": 0.968,
    "F-score-macro": 0.622,
    "F-score-micro": 0.968
}
araBERT_ft_wl = {
    "number_step": 8,
    "name_model": "Fine-tuning with WL",
    "features": "Contextual subword embeddings",
    "parameters_model": "Fine-tuning + class weights",
    "methods_preprocessing": "tokenization + padding",
    "accuracy": 0.969,
    "F-score-macro": 0.877,
    "F-score-micro": 0.969
}
dictionary.append(araBERT_base)
dictionary.append(araBERT_ft)
dictionary.append(araBERT_ft_wl)

"""

> # Cmoparing the Best Models (Weighted BiLSTM, CBOW embedding, weighted araBERT with Fine-tuning)

"""

import matplotlib.pyplot as plt
import numpy as np
models = ["Weighted BiLSTM", "CBOW embedding","araBERT - Fine-tuning with WL"]
# macro_f1 = [0.106, 0.266,0.412]
# micro_f1 = [0.167, 0.598,0.943]
# masked_acc = [0.17, 0.60,0.9510]
macro_f1 = [0.412, 0.522,0.877]
micro_f1 = [0.943, 0.927,0.969]
masked_acc = [0.9510,0.927,0.969]

x = np.arange(len(models))
width = 0.25

plt.figure(figsize=(8,5))
plt.bar(x - width, macro_f1, width, label="Macro F1")
plt.bar(x, micro_f1, width, label="Micro F1")
plt.bar(x + width, masked_acc, width, label="Masked Accuracy")

plt.xticks(x, models)
plt.ylabel("Score")
plt.title("Weighted BiLSTM vs CBOW embedding vs araBERT - Fine-tuning with WL")
plt.legend()
plt.grid(axis="y", linestyle="--", alpha=0.6)
plt.show()

"""النموذج araBERT أبدى أقوى قيم من الدقة و F1-score

The Best Model among them is *araBERT - Fine-tuning with WL*

# الآن لنختبر النموذج على داتا جديدة لم يتعلم عليها مسبقاً ونعرض مصفوفة التعارض  *araBERT - Fine-tuning with WL*

# Load new Data to test the model for confusion matrix
"""

from transformers import AutoModelForTokenClassification, AutoTokenizer

path = "/content/drive/MyDrive/arabert_finetuned_model_wieghtedLoss_MEDICAL_2"

tokenizer = AutoTokenizer.from_pretrained(path)

model = AutoModelForTokenClassification.from_pretrained(path)

import pandas as pd
import gdown

# url = "https://drive.google.com/uc?id=1sQppeJ4RMzuUmwaZFe7Xfa2q8kiImWR6"
# dataset_path = "/tmp/dataset.csv"

# gdown.download(url, dataset_path, quiet=False)

chunks_new = pd.read_csv("/content/drive/MyDrive/F_dataset/dataset.csv", skiprows=range(1, 400001), chunksize=200000)

chunks_new = next(chunks_new)
chunks_new.sample(10)

X = chunks_new["word"].tolist()
Y = chunks_new["label_id"].tolist()

for i in range(10):
    print(X[i], "->", Y[i])

def sequence(words, labels):
    X, Y = [], []
    sent, sent_labels = [], []

    for word, label in zip(words, labels):
        sent.append(word)
        sent_labels.append(label)

        if label in [1, 3, 4]:  # . ؟ !
            X.append(sent)
            Y.append(sent_labels)
            sent, sent_labels = [], []

    if len(sent) > 0:
        X.append(sent)
        Y.append(sent_labels)

    return X, Y

X, Y = sequence(X, Y)

print(X[0])
print(Y[0])

clean_X, clean_Y = [], []

for sent, labels in zip(X, Y):
    new_sent, new_labels = [], []

    for w, l in zip(sent, labels):
        if isinstance(w, str) and w.strip() != "":
            new_sent.append(w)
            new_labels.append(l)

    if len(new_sent) > 0:
        clean_X.append(new_sent)
        clean_Y.append(new_labels)

print("Deleted samples:", len(X) - len(clean_X))

X = clean_X
Y = clean_Y

def encode_sentence(words, labels, max_len=64):
    encoding = tokenizer(
        words,
        is_split_into_words=True,
        truncation=True,
        padding="max_length",
        max_length=max_len,
        return_tensors="pt"
    )

    word_ids = encoding.word_ids()
    label_ids = []
    previous_word_idx = None

    for word_idx in word_ids:
        if word_idx is None:
            label_ids.append(-100)
        elif word_idx != previous_word_idx:
            label_ids.append(labels[word_idx])
        else:
            label_ids.append(-100)
        previous_word_idx = word_idx

    encoding["labels"] = torch.tensor(label_ids)
    return encoding

encoded_data = []
# max_len = max(len(s) for s in X)
for sent, lab in zip(X, Y):
    encoded_data.append(encode_sentence(sent, lab,max_len=128))

from sklearn.model_selection import train_test_split

train_data, val_data = train_test_split(
    encoded_data,
    test_size=0.1,
    random_state=42
)

class PunctuationDataset(torch.utils.data.Dataset):
    def __init__(self, data):
        self.data = data

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        return {k: v.squeeze(0) for k, v in self.data[idx].items()}

train_dataset = PunctuationDataset(train_data)
val_dataset   = PunctuationDataset(val_data)

"""

> # Now to test the best mdoel and dreaw Confising Metrix
"""

import numpy as np

def get_predictions(model, dataset, device):
    all_labels = []
    all_preds = []

    with torch.no_grad():
        for batch in dataset:
            input_ids = batch["input_ids"].unsqueeze(0).to(device)
            attention_mask = batch["attention_mask"].unsqueeze(0).to(device)
            labels = batch["labels"].unsqueeze(0).to(device)

            outputs = model(
                input_ids=input_ids,
                attention_mask=attention_mask
            )

            preds = torch.argmax(outputs.logits, dim=-1)

            # flatten + ignore padding
            for p, l in zip(preds.view(-1), labels.view(-1)):
                if l != -100:
                    all_preds.append(p.item())
                    all_labels.append(l.item())

    return np.array(all_labels), np.array(all_preds)

import torch
import numpy as np
from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)
model.eval()
labels, preds = get_predictions(model, val_dataset, device)
cm = confusion_matrix(labels, preds)

plt.figure(figsize=(8,6))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues")
plt.xlabel("Predicted")
plt.ylabel("True")
plt.title("Confusion Matrix")
plt.show()

from sklearn.metrics import f1_score

def evaluate_macro_f1(model, dataloader, device,labels,preds):
    # labels, preds = get_predictions(model, dataloader, device)
    return f1_score(labels, preds, average="macro")
def evaluate_wighted_f1(model, dataloader, device,labels,preds):
    # labels, preds = get_predictions(model, dataloader, device)
    return f1_score(labels, preds, average="weighted")
test_macro_f1 = evaluate_macro_f1(model, val_dataset, device,labels,preds)
test_weighted_f1 = evaluate_wighted_f1(model, val_dataset, device,labels,preds)

print(f"Test Macro-F1:       {test_macro_f1:.4f}")
print(f"Test Weighted-F1:    {test_weighted_f1:.4f}")

"""

> # Train on medcine dataset

"""

from datasets import load_dataset

dataset_name = "Ahmed-Selem/Shifaa_Arabic_Medical_Consultations"

try:
    dataset = load_dataset(dataset_name)
    print(f"Successfully downloaded dataset: {dataset_name}")
    print(dataset)
except Exception as e:
    print(f"Error downloading dataset {dataset_name}: {e}")

import pandas as pd

df = dataset['train'].to_pandas()
print("Dataset converted to pandas DataFrame. Displaying the first 5 rows:")
# display(df.head())

df['Main Category'] = df['Hierarchical Diagnosis'].apply(lambda x: x.split(' - ')[0] if isinstance(x, str) and ' - ' in x else x)

print("Added 'main category' column. Displaying the first 5 rows with the new column:")
display(df.head())

internal_med_ds = df[
    df["Main Category"] == "أمراض الباطنية والصدر"
]

print("Number of internal medicine samples:", len(internal_med_ds))
display(internal_med_ds.head())

# internal_med_ds.to_csv("shifaa_internal_medicine.csv")

import re

punct = {'.':1,'،':2,'؟':3,'!':4,':':5,'؛':6,' ':0}

def encoding_word_medcine(example):
    text = (
        example.get("Question Title", "") + " " +
        example.get("Question", "") + " " +
        example.get("Answer", "")
    )

    text = re.sub(r"\s+", " ", text).strip()

    words = text.split()

    words_without_puncts = []
    label_ids = []

    for word in words:
        match = re.match(r"(.*?)([،\.\؟\!\:\؛])?$", word)
        clean = match.group(1)
        puncts = match.group(2) if match.group(2) in punct else " "

        words_without_puncts.append(clean)
        label_ids.append(punct[puncts])

    return {
        "word": words_without_puncts,
        "label_id": label_ids
    }
encoded_rows = internal_med_ds.apply(encoding_word_medcine, axis=1)

X = encoded_rows.apply(lambda x: x["word"]).tolist()
Y = encoded_rows.apply(lambda x: x["label_id"]).tolist()

print(len(X), len(Y))
print(X[0][:20])
print(Y[0][:20])

from transformers import AutoModelForTokenClassification, AutoTokenizer

path = "/content/drive/MyDrive/arabert_finetuned_model_wieghtedLoss"

tokenizer = AutoTokenizer.from_pretrained(path)

model = AutoModelForTokenClassification.from_pretrained(path)

import torch
def encode_sentence(words, labels, max_len=128):
    encoding = tokenizer(
        words,
        is_split_into_words=True,
        truncation=True,
        padding="max_length",
        max_length=max_len,
        return_tensors="pt"
    )

    word_ids = encoding.word_ids()
    label_ids = []
    previous_word_idx = None

    for word_idx in word_ids:
        if word_idx is None:
            label_ids.append(-100)
        elif word_idx != previous_word_idx:
            label_ids.append(labels[word_idx])
        else:
            label_ids.append(-100)
        previous_word_idx = word_idx

    encoding["labels"] = torch.tensor(label_ids)
    return encoding
encoded_data =[]
for sent, lab in zip(X, Y):
    encoded_data.append(encode_sentence(sent, lab, max_len=128))

print(len(encoded_data))
print(encoded_data[0].keys())

from sklearn.model_selection import train_test_split

train_data, val_data = train_test_split(
    encoded_data,
    test_size=0.3,
    random_state=42
)
class PunctuationDataset(torch.utils.data.Dataset):
    def __init__(self, data):
        self.data = data

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        return {k: v.squeeze(0) for k, v in self.data[idx].items()}
train_dataset = PunctuationDataset(train_data)
val_dataset   = PunctuationDataset(val_data)

import numpy as np
from sklearn.metrics import accuracy_score, f1_score

def compute_metrics(eval_pred):
    logits = eval_pred.predictions
    labels =  eval_pred.label_ids
    predictions = np.argmax(logits, axis=-1)

    true_labels = []
    true_preds  = []

    for pred_seq, label_seq in zip(predictions, labels):
        for p, l in zip(pred_seq, label_seq):
            if l != -100:
                true_labels.append(l)
                true_preds.append(p)

    accuracy = accuracy_score(true_labels, true_preds)
    micro_f1 = f1_score(true_labels, true_preds, average="micro")
    macro_f1 = f1_score(true_labels, true_preds, average="macro")

    return {
        "accuracy": accuracy,
        "micro_f1": micro_f1,
        "macro_f1": macro_f1
    }

import torch
import torch.nn.functional as F
from transformers import Trainer

class_weights = torch.tensor([0.1, 1.0, 1.3, 3.0, 2.5, 3.2, 3.5], dtype=torch.float)

class WeightedTrainer(Trainer):
    def compute_loss(self, model, inputs, return_outputs=False, **kwargs):
        labels = inputs.pop("labels")
        outputs = model(**inputs)
        logits = outputs.logits

        loss = F.cross_entropy(
            logits.view(-1, model.config.num_labels),
            labels.view(-1),
            weight=class_weights.to(logits.device),
            ignore_index=-100
        )

        return (loss, outputs) if return_outputs else loss

from transformers import Trainer, TrainingArguments

training_args = TrainingArguments(
    output_dir="./results",
    eval_strategy="epoch",
    save_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    num_train_epochs=5,
    weight_decay=0.01,
    logging_steps=100,
    load_best_model_at_end=True,
    metric_for_best_model="macro_f1",
    greater_is_better=True,
    report_to="none",
    fp16 = True
)

from transformers import EarlyStoppingCallback

trainer = WeightedTrainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    tokenizer=tokenizer,
    compute_metrics=compute_metrics,
        callbacks=[EarlyStoppingCallback(early_stopping_patience=2)]

)

trainer.train()

preds = trainer.predict(val_dataset)
compute_metrics(preds)

import matplotlib.pyplot as plt
logs = trainer.state.log_history
df = pd.DataFrame(logs)

train_loss = df[df["loss"].notna()][["epoch", "loss"]]
val_loss   = df[df["eval_loss"].notna()][["epoch", "eval_loss"]]

plt.figure(figsize=(8,5))

plt.plot(train_loss["epoch"], train_loss["loss"], label="Train Loss (with FT)")
plt.plot(val_loss["epoch"], val_loss["eval_loss"], label="Val Loss (with FT)")



plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.title("Training vs Validation Loss")
plt.legend()
plt.grid(True)
plt.show()

metrics = df[df["eval_accuracy"].notna()][
    ["epoch", "eval_accuracy", "eval_micro_f1", "eval_macro_f1"]
]

plt.figure(figsize=(8,5))

plt.plot(metrics["epoch"], metrics["eval_macro_f1"], label="eval_macro_f1 (with FT)")

plt.xlabel("Epoch")
plt.ylabel("macro f1")
plt.title("Validation macro f1")
plt.legend()
plt.grid(True)
plt.show()

plt.figure(figsize=(8,5))

plt.plot(metrics["epoch"], metrics["eval_micro_f1"], label="eval micro f1 (with FT)")

plt.xlabel("Epoch")
plt.ylabel("micro f1")
plt.title("Validation micro f1")
plt.legend()
plt.grid(True)
plt.show()

# trainer.save_model("/content/drive/MyDrive/arabert_weighted")
from transformers import AutoModelForTokenClassification, AutoTokenizer

path = "/content/drive/MyDrive/arabert_finetuned_model_wieghtedLoss_MEDICAL"

model.save_pretrained(path)
tokenizer.save_pretrained(path)

from datasets import load_dataset

dataset_name = "Ahmed-Selem/Shifaa_Arabic_Medical_Consultations"

try:
    dataset = load_dataset(dataset_name)
    # print(f"Successfully downloaded dataset: {dataset_name}")
    print(dataset)
except Exception as e:
    print(f"Error downloading dataset {dataset_name}: {e}")

import pandas as pd

df = dataset['train'].to_pandas()
# print("Dataset converted to pandas DataFrame. Displaying the first 5 rows:")
# display(df.head())

df['Main Category'] = df['Hierarchical Diagnosis'].apply(lambda x: x.split(' - ')[0] if isinstance(x, str) and ' - ' in x else x)
Physical_med_ds = df[
    df["Main Category"] =="الصحة البدنية"
]

print("Number of Physical medicine samples:", len(Physical_med_ds))
display(Physical_med_ds.head())

encoded_rows = Physical_med_ds.apply(encoding_word_medcine, axis=1)

X = encoded_rows.apply(lambda x: x["word"]).tolist()
Y = encoded_rows.apply(lambda x: x["label_id"]).tolist()
encoded_data =[]
for sent, lab in zip(X, Y):
    encoded_data.append(encode_sentence(sent, lab, max_len=128))

train_data, val_data = train_test_split(
    encoded_data,
    test_size=0.1,
    random_state=42
)
train_dataset = PunctuationDataset(train_data)
val_dataset   = PunctuationDataset(val_data)

trainer.train_dataset = train_dataset
trainer.eval_dataset = val_dataset
trainer.train()

preds = trainer.predict(val_dataset)
compute_metrics(preds)

import matplotlib.pyplot as plt
logs = trainer.state.log_history
df = pd.DataFrame(logs)

train_loss = df[df["loss"].notna()][["epoch", "loss"]]
val_loss   = df[df["eval_loss"].notna()][["epoch", "eval_loss"]]

plt.figure(figsize=(8,5))

plt.plot(train_loss["epoch"], train_loss["loss"], label="Train Loss (with FT)")
plt.plot(val_loss["epoch"], val_loss["eval_loss"], label="Val Loss (with FT)")



plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.title("Training vs Validation Loss")
plt.legend()
plt.grid(True)
plt.show()

metrics = df[df["eval_accuracy"].notna()][
    ["epoch", "eval_accuracy", "eval_micro_f1", "eval_macro_f1"]
]

plt.figure(figsize=(8,5))

plt.plot(metrics["epoch"], metrics["eval_macro_f1"], label="eval_macro_f1 (with FT)")

plt.xlabel("Epoch")
plt.ylabel("macro f1")
plt.title("Validation macro f1")
plt.legend()
plt.grid(True)
plt.show()

plt.figure(figsize=(8,5))

plt.plot(metrics["epoch"], metrics["eval_micro_f1"], label="eval micro f1 (with FT)")

plt.xlabel("Epoch")
plt.ylabel("micro f1")
plt.title("Validation micro f1")
plt.legend()
plt.grid(True)
plt.show()

import torch
import numpy as np
from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)
model.eval()
labels, preds = get_predictions(model, val_dataset, device)
cm = confusion_matrix(labels, preds)

plt.figure(figsize=(8,6))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues")
plt.xlabel("Predicted")
plt.ylabel("True")
plt.title("Confusion Matrix")
plt.show()

from transformers import AutoModelForTokenClassification, AutoTokenizer

path = "/content/drive/MyDrive/arabert_finetuned_model_wieghtedLoss_MEDICAL_2"

model.save_pretrained(path)
tokenizer.save_pretrained(path)

araBERT_ft_wl_MedData = {
    "number_step": 9,
    "name_model": "Fine-tuning with WL",
    "features": "Contextual subword embeddings",
    "parameters_model": "Fine-tuning + class weights",
    "methods_preprocessing": "tokenization + padding",
    "accuracy": 0.937,
    "F-score-macro": 0.766,
    "F-score-micro": 0.937
}
dictionary.append(araBERT_ft_wl_MedData)

dictionary

from google.colab import drive
drive.mount('/content/drive')

import torch
from transformers import AutoTokenizer, AutoModelForTokenClassification
from sklearn.metrics import accuracy_score, f1_score, classification_report, confusion_matrix
import gdown
import re
import os
def encoding_word(texts):
  words_without_puncts = []
  leabels = []
  l_id=[]
  punct = {'.':1,'،':2,'؟':3,'!':4,':':5,'؛':6,' ':0}
  words = texts.split()
  for word in words:
    match = re.match(r"(.*?)([،\.\؟\!\:\؛])?$", word)
    clean = match.group(1)
    puncts_in_phrase = match.group(2) or " "
    words_without_puncts.append(clean)
    leabels.append(puncts_in_phrase)
    # print(leabels)
  l_id=[punct[p] for p in leabels]
  # df = pd.DataFrame({
  # "word": words_without_puncts,
  # "punct": leabels,
  # "label_id": l_id
  # })
  return words_without_puncts,l_id


# def adapt_input(data):
#     if isinstance(data, pd.DataFrame):
#         return data

#     if isinstance(data, str):
#         return encoding_word(data)

#     raise TypeError("Input must be DataFrame or raw text")

def sequence(words, labels, max_len=128):
    X, Y = [], []
    for i in range(0, len(words), max_len):
        X.append(words[i:i+max_len])
        Y.append(labels[i:i+max_len])
    return X, Y

def encode_sentence(words, labels, tokenizer,max_len=128):
    encoding = tokenizer(
        words,
        is_split_into_words=True,
        truncation=True,
        padding="max_length",
        max_length=max_len,
        return_tensors="pt"
    )

    word_ids = encoding.word_ids()
    label_ids = []
    previous_word_idx = None

    for word_idx in word_ids:
        if word_idx is None:
            label_ids.append(-100)
        elif word_idx != previous_word_idx:
            label_ids.append(labels[word_idx])
        else:
            label_ids.append(-100)
        previous_word_idx = word_idx

    encoding["labels"] = torch.tensor(label_ids)
    return encoding

class PunctuationDataset(torch.utils.data.Dataset):
  def __init__(self, data):
      self.data = data

  def __len__(self):
      return len(self.data)

  def __getitem__(self, idx):
      return {k: v.squeeze(0) for k, v in self.data[idx].items()}

import matplotlib.pyplot as plt
import seaborn as sns


def evaluate_best_model(test_dataset_url, model_path):
    texts = []
    if test_dataset_url.startswith("http"):
        local_dir = "/tmp/test_data"
        gdown.download_folder(
            test_dataset_url,
            output=local_dir,
            quiet=True,
            use_cookies=False
        )
        test_dataset_url = local_dir
    if os.path.isdir(test_dataset_url):
        for file in sorted(os.listdir(test_dataset_url)):
            if file.endswith(".txt"):
                file_path = os.path.join(test_dataset_url, file)
                with open(file_path, "r", encoding="utf-8") as f:
                    texts.append(f.read())
    elif os.path.isfile(test_dataset_url):
        with open(test_dataset_url, "r", encoding="utf-8") as f:
            texts.append(f.read())

    else:
        raise ValueError("Invalid dataset path or URL")

    text = "\n\n".join(texts)
    X,Y = encoding_word(text)
    # X = df["word"].tolist()
    # Y = df["label_id"].tolist()
    X,Y=sequence(X,Y)

    tokenizer = AutoTokenizer.from_pretrained(model_path)
    model = AutoModelForTokenClassification.from_pretrained(model_path)

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model.to(device)
    model.eval()


    test_encoded_data = []
    for sent, lab in zip(X, Y):
      test_encoded_data.append(encode_sentence(sent, lab,tokenizer, max_len=128))

    test_dataset = PunctuationDataset(test_encoded_data)



    all_preds = []
    all_labels = []

    test_loader = torch.utils.data.DataLoader(
        test_dataset,
        batch_size=4,
        shuffle=False
    )

    with torch.no_grad():
        for batch in test_loader:
            input_ids = batch["input_ids"].to(device)
            attention_mask = batch["attention_mask"].to(device)
            labels = batch["labels"].to(device)

            outputs = model(
                input_ids=input_ids,
                attention_mask=attention_mask
            )

            predictions = torch.argmax(outputs.logits, dim=-1)

            preds = predictions.cpu().numpy()
            true_labels = labels.cpu().numpy()

            for p, t in zip(preds, true_labels):
                for pred_label, true_label in zip(p, t):
                    if true_label != -100:
                        all_preds.append(pred_label)
                        all_labels.append(true_label)

    accuracy = accuracy_score(all_labels, all_preds)
    f1 = f1_score(all_labels, all_preds, average="macro")
    f1_micro = f1_score(all_labels, all_preds, average="micro")
    f1_weighted = f1_score(all_labels, all_preds, average="weighted")

    print(" نتائج التقييم:")
    print(f"Accuracy = {accuracy:.4f}")
    print(f"F1-score-macro = {f1:.4f}")
    print(f"F1-score-micro = {f1_micro:.4f}")
    print(f"F1-score-weighted = {f1_weighted:.4f}")
    print("\nClassification Report:\n")
    print(classification_report(all_labels, all_preds))


    cm = confusion_matrix(all_labels, all_preds)
    plt.figure(figsize=(8,6))
    sns.heatmap(cm, annot=True, fmt="d", cmap="Blues")
    plt.xlabel("Predicted")
    plt.ylabel("True")
    plt.title("Confusion Matrix")
    plt.show()
    return f1

# BEST_MODEL_PATH = "/content/drive/MyDrive/arabert_finetuned_model_wieghtedLoss"
BEST_MODEL_PATH = "/content/drive/MyDrive/arabert_finetuned_model_wieghtedLoss_MEDICAL_2"
Test_data = "/content/drive/MyDrive/ABC/ABC"
#https://drive.google.com/drive/folders/1QUtrSPhvsRZtdcjbe8uv-oOToLWiVOjy?usp=drive_link
evaluate_best_model(Test_data, BEST_MODEL_PATH)

